In [1]:
import numpy as np

In [19]:
arr = np.array([5,5,5,5,5,5,5,5,5,5])

print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [20]:
j=0
arr1 = np.array([])
for i in range(10,50):
  if i%2==0:
    arr1=np.append(arr1, [i])
    j+=1

print(arr1)    

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48.]


In [21]:
mat = np.matrix([[1,2,3,4],[2,3,4,1,],[3,4,1,2,],[4,1,2,3]])

print(mat)

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]
 [4 1 2 3]]


In [22]:
arr2 = np.random.normal(0,1,25)

print(arr2)

[-0.49835908  0.94058176 -0.26215615 -0.8492006   1.93373789  2.01904092
  0.37161673  0.51291343 -0.05285255 -0.41937593 -1.13427193 -0.15534678
 -1.71085125 -0.45169232 -1.32604554 -0.00359166  0.87326997 -0.66148973
 -0.56753517 -0.87309228 -0.85120632  0.29656046 -0.5662476  -0.67353326
 -0.81474355]


In [32]:
array = np.arange(1,26).reshape(5,5)

print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [34]:
print(array[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [35]:
print(array[3,4])

20


In [37]:
print(array[0:3,1])

[ 2  7 12]


In [38]:
np.std(array)

7.211102550927978

In [39]:
array.sum(axis=0)

array([55, 60, 65, 70, 75])